### PR TITLE
Initial helm chart

### LINKED ISSUE #19: Helm chart for deployment
I might take a stab at this soon, but wanted to ask if you had ideas on this already.

### PR DESCRIPTION
**Pull request by nogweii**
Just using the base template and merging your example into it. Successfully deploys to my homelab. Haven't actually tested the operator itself though. :sweat_smile: 

Closes #19.

Possible TODOs:

- [ ] 1. Include [`helm-docs`](https://github.com/norwoodj/helm-docs) as another asset to download
- [ ] 2. Set up a github workflow for chart publishing to github pages
- [ ] 3. Does this chart actually create any `Minio*` resources? e.g. is there a default bucket it will create?
      If so, the CRDs will likely need to be split apart into a separate chart so that they can be installed independently of any custom resources actually created by helm.
- [ ] 4. Documentation on using helm
- [ ] 5. I'd like to be able to generate the CRDs into individual files, for eventual setup with [jsonnet-libs](https://github.com/jsonnet-libs/k8s). (A tool to automatically generate Jsonnet libraries derived from CRDs, which I use a lot in my own infrastructure.)
- [ ] 6. Fix the makefile in case I broke something by removing the example deployment

### CODE REVIEW

**Comment by benfiola** [comment]
Thank you so much for putting the time into working on this!  🥳 

>  2. Set up a github workflow for chart publishing to github pages

Yeah!  This will be really interesting - I know others are using github pages as their 'Helm chart repo' frontend - and while I have a rough idea of the plumbing required to make it work, I'll need to actually sit down and figure it out.  I'll try to spend some time doing so tomorrow - work's been a bit busy lately.

>  3. Does this chart actually create any Minio* resources?

For simplicity, maybe we start without including any default resources - and if, over time, people find that they expect this chart to produce default resources, we can revisit this and/or gate it behind a values.yaml key? 

> 4.  Documentation on using helm

Yeah, I think this would slot nicely under the _Installation_ section.  In fact, I'd say the barrier to entry is lowered through helm - so thanks again for creating this foundation.

> 5. I'd like to be able to generate the CRDs into individual files, for eventual setup with [jsonnet-libs](https://github.com/jsonnet-libs/k8s).

While this operator is inspired by [kubebuilder](https://book.kubebuilder.io/), I avoided using their high-level codegen directly because I felt like it was a bit heavy on the boilerplate.  _However_, one thing I've been wanting to adopt was their CRD code-gen from comment markers.  Maybe this is something I can tackle to give you a better entry point into your own code-gen.

**Comment by benfiola** [comment]
> While this operator is inspired by [kubebuilder](https://book.kubebuilder.io/), I avoided using their high-level codegen directly because I felt like it was a bit heavy on the boilerplate. _However_, one thing I've been wanting to adopt was their CRD code-gen from comment markers. Maybe this is something I can tackle to give you a better entry point into your own code-gen.

Following up on this - I've created the following [PR](https://github.com/benfiola/minio-operator-ext/pull/23) that uses `controller-gen` to generate CRD (and RBAC) files.  How would you be ingesting these CRD files into `jsonnet-libs`?

**Comment by benfiola** [comment]
> Yeah! This will be really interesting - I know others are using github pages as their 'Helm chart repo' frontend - and while I have a rough idea of the plumbing required to make it work, I'll need to actually sit down and figure it out. I'll try to spend some time doing so tomorrow - work's been a bit busy lately.

Following up on this - I've created the following [PR](https://github.com/benfiola/minio-operator-ext/pull/24) that:

* Has blank template charts in `charts/operator` and `charts/crds`
* Augments the publishing workflow to 'publish' these charts to the `gh-pages` branch.

Ultimately, this means you can point helm to the repo `https://benfiola.github.io/minio-operator-ext` and helm should work just fine.

**Comment by benfiola** [comment]
Since your changes currently implement the charts themselves - I'll merge my changes into `dev` and if you'd like to rebase your changes on top of them, your code can be the final (?) piece for helm chart support.

**Comment by nogweii** [comment]
@benfiola I've updated the PR to put my chart work into the charts/ subfolders. Let me know what you think!

**Comment by benfiola** [comment]
Changes look good - is there any way you can squash your commits into a single one and give it a semantic commit like: `feat: implement helm charts` or something to that effect?

This repo uses semantic commits to determine version bumps.

**Comment by benfiola** [comment]
And again, thank you for all the hard work!

**Review by benfiola — APPROVED** [review]

**Pull request merged**
